import org.jetbrains.compose.desktop.application.dsl.TargetFormat
import org.jetbrains.kotlin.gradle.ExperimentalWasmDsl
import org.jetbrains.kotlin.gradle.dsl.JvmTarget
import java.util.Properties

plugins {
    alias(libs.plugins.kotlinMultiplatform)
    alias(libs.plugins.androidApplication)
    alias(libs.plugins.composeMultiplatform)
    alias(libs.plugins.composeCompiler)
    alias(libs.plugins.composeHotReload)
    id("com.google.gms.google-services")
    kotlin("plugin.serialization") version "2.1.21"
}

// ---- Build-time Environment (dev/prod) ------------------------------------
// Select profile with `-Penv=dev` (default) or `-Penv=prod`.
//
// Cascade di lettura per ogni chiave (pattern KMP standard):
//   1. local.properties        → sviluppo locale (gitignored, mai committato)
//   2. System.getenv(KEY)       → CI/CD (GitHub Actions secrets) e produzione
//   3. findProperty(KEY)        → gradle.properties (committed, default safe)
//   4. default hardcoded        → ultimo fallback
//
// gradle.properties resta statico e committato con valori safe (es.
// API_BASE_URL=https://example.com). I segreti (signing keystore, URL prod
// reali) vivono SOLO in local.properties locale o in env vars iniettate
// dalla CI/piattaforma di deploy. Il build.gradle.kts non si tocca per cambiare
// ambiente: basta cambiare la sorgente.

fun stripQuotes(s: String): String = s.trim().trim('"')
fun parseBaseUrl(url: String): Pair<String, String> {
    val trimmed = url.removeSuffix("/")
    return when {
        trimmed.startsWith("https://") -> "https" to trimmed.removePrefix("https://")
        trimmed.startsWith("http://") -> "http" to trimmed.removePrefix("http://")
        else -> "https" to trimmed
    }
}

// Carica local.properties se presente (gitignored di default in KMP/Android).
val localProps: Properties = Properties().also { props ->
    val f = rootProject.file("local.properties")
    if (f.exists()) f.inputStream().use { props.load(it) }
}

// Cascade helper: local.properties → env var → gradle property → default.
fun envOrLocal(key: String, default: String? = null): String? =
    localProps.getProperty(key)
        ?: System.getenv(key)
        ?: (findProperty(key) as String?)
        ?: default

val envProfile: String =
    (findProperty("env") as String?)
        ?: stripQuotes(envOrLocal("ENV_MODE", "dev")!!)

val devHost: String = stripQuotes(envOrLocal("DEV_URL", "localhost")!!)
val stagingHost: String = stripQuotes(envOrLocal("STAGING_URL", "localhost")!!)
val devPort: String = envOrLocal("DEV_PORT", "10000")!!
val stagingPort: String = envOrLocal("STAGING_PORT", "10000")!!
val prodBase: String = stripQuotes(envOrLocal("API_BASE_URL", "https://example.com")!!)
val prodPort: String = envOrLocal("PROD_PORT", "443")!!

val envScheme: String = if (envProfile == "prod") parseBaseUrl(prodBase).first else "http"
val envHost: String = if (envProfile == "prod") parseBaseUrl(prodBase).second else if(envProfile == "staging") stagingHost else devHost
val envPort: String = if (envProfile == "prod") prodPort else if(envProfile == "staging") stagingPort else devPort

val generateEnvironment = tasks.register("generateEnvironment") {
    val outDir = layout.buildDirectory.dir("generated/environment/commonMain")
    outputs.dir(outDir)
    inputs.property("profile", envProfile)
    inputs.property("scheme",  envScheme)
    inputs.property("host",    envHost)
    inputs.property("port",    envPort)
    val capturedScheme = envScheme
    val capturedHost = envHost
    val capturedPort = envPort
    val capturedProfile = envProfile
    doLast {
        val dir = outDir.get().asFile.resolve("homeaq/dothattask/dothattask_fe/dothattask_fe/Config")
        dir.mkdirs()
        dir.resolve("Environment.kt").writeText(
            """
            package homeaq.dothattask.dothattask_fe.dothattask_fe.Config

            // Auto-generated by :composeApp:generateEnvironment. Do not edit by hand.
            object Environment {
                const val PROFILE: String = "$capturedProfile"
                const val SCHEME: String = "$capturedScheme"
                const val HOST: String = "$capturedHost"
                const val PORT: Int = $capturedPort
            }
            """.trimIndent(),
        )
    }
}

kotlin {
    androidTarget {
        compilerOptions {
            jvmTarget.set(JvmTarget.JVM_11)
        }
    }

    listOf(
        iosArm64(),
        iosSimulatorArm64()
    ).forEach { iosTarget ->
        iosTarget.binaries.framework {
            baseName = "ComposeApp"
            isStatic = true
        }
    }

    jvm()
    sourceSets {
        jvmMain.dependencies {
            implementation(compose.desktop.currentOs)
        }
    }

    js {
        browser()
        binaries.executable()
    }

    @OptIn(ExperimentalWasmDsl::class)
    wasmJs {
        browser()
        binaries.executable()
    }

    sourceSets {
        commonMain {
            kotlin.srcDir(generateEnvironment.map { layout.buildDirectory.dir("generated/environment/commonMain") })
        }
        androidMain.dependencies {
            implementation(compose.preview)
            implementation(libs.androidx.activity.compose)

            implementation(libs.ktor.client.android)
            implementation(libs.androidx.work.runtime.ktx.v290)
            implementation(libs.androidx.security.crypto)
        }
        commonMain.dependencies {
            implementation(compose.runtime)
            implementation(compose.foundation)
            implementation(compose.material3)
            implementation(compose.ui)
            implementation(compose.components.resources)
            implementation(compose.components.uiToolingPreview)
            implementation(libs.androidx.lifecycle.viewmodelCompose)
            implementation(libs.androidx.lifecycle.runtimeCompose)

            implementation(libs.kotlinx.serialization.json)

            implementation(libs.ktor.client.core)
            implementation(libs.ktor.client.auth)
            implementation(libs.ktor.client.content.negotiation)
            implementation(libs.ktor.serialization.kotlinx.json)




        }
        commonTest.dependencies {
            implementation(libs.kotlin.test)
        }

        jvmMain.dependencies {
            implementation(compose.desktop.currentOs)
            implementation(libs.kotlinx.coroutinesSwing)
            implementation(libs.ktor.client.cio)
        }


        jsMain.dependencies {
            implementation(libs.ktor.client.js)
        }

        wasmJsMain.dependencies {
            implementation(libs.ktor.client.wasm)
        }

        iosMain.dependencies {
            implementation(libs.ktor.client.darwin)
        }
    }
}

android {
    namespace = "homeaq.dothattask.dothattask_fe.dothattask_fe"
    compileSdk = libs.versions.android.compileSdk.get().toInt()


    defaultConfig {
        applicationId = "homeaq.dothattask.dothattask_fe.dothattask_fe"
        minSdk = libs.versions.android.minSdk.get().toInt()
        targetSdk = libs.versions.android.targetSdk.get().toInt()
        versionCode = 3
        versionName = "1.4.1"
    }
    packaging {
        resources {
            excludes += "/META-INF/{AL2.0,LGPL2.1}"
        }
    }

    //this is to sign the Android APK
    // Credenziali lette via cascata: local.properties → env vars (CI) → gradle.properties.
    signingConfigs {
        val storeFilePath = envOrLocal("RELEASE_STORE_FILE")
        if (storeFilePath != null) {
            create("release_debug") {   // <<< usa create() invece di "release { ... }"
                storeFile = file(storeFilePath)
                storePassword = envOrLocal("RELEASE_STORE_PASSWORD") ?: ""
                keyAlias = envOrLocal("RELEASE_KEY_ALIAS") ?: ""
                keyPassword = envOrLocal("RELEASE_KEY_PASSWORD") ?: ""
            }
        }
    }

    buildTypes {
        getByName("release") {
            isMinifyEnabled = false
            if (envOrLocal("RELEASE_STORE_FILE") != null) {
                signingConfig = signingConfigs.getByName("release_debug")
            }
            isDebuggable = true
            isJniDebuggable = true

        }
    }
    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_11
        targetCompatibility = JavaVersion.VERSION_11
    }
}

dependencies {
    implementation(platform("com.google.firebase:firebase-bom:34.12.0"))
    implementation("com.google.firebase:firebase-analytics")
    // FCM — server-driven push notifications (replaces the old Android-only
    // DailyNotificationWorker). Requires google-services.json at composeApp/.
    implementation("com.google.firebase:firebase-messaging")
    debugImplementation(compose.uiTooling)
}

compose.desktop {
    application {
        mainClass = "homeaq.dothattask.dothattask_fe.dothattask_fe.MainKt"

        nativeDistributions {
            targetFormats(TargetFormat.Dmg, TargetFormat.Msi, TargetFormat.Deb)
            packageName = "Do That Task"
            // MUST be bumped on every release. Windows Installer only triggers
            // a Major Upgrade when the new MSI's version is greater than the
            // installed one. Use semantic versioning (X.Y.Z); a fourth
            // component is allowed but Compose forwards this verbatim to
            // jpackage which forwards it to WiX.
            packageVersion = "1.4.1"
            includeAllModules = true
            windows {
                iconFile.set(File("logo/icon.ico"))
                // Per-user install (no admin prompt). The trade-off is that
                // upgrade detection only matches *previous per-user installs*;
                // a system-wide install (perUserInstall=false) cannot be
                // upgraded by this MSI and would have to be removed first.
                perUserInstall = true
                dirChooser = true
                menuGroup = "DoThatTask"
                // Same UpgradeCode forever — this is what lets a new MSI
                // detect the previously installed version and run a Major
                // Upgrade (silently uninstall + install) instead of failing
                // with "another version is already installed". Never change
                // this value: doing so breaks every future upgrade.
                upgradeUuid = "A1B2C3D4-E5F6-7890-ABCD-EF1234567890"
                shortcut = true
            }
            modules("java.instrument", "java.management", "java.naming", "java.sql", "jdk.unsupported")
        }
        buildTypes.release.proguard {
            isEnabled.set(false)
        }
    }
}
