import org.jetbrains.compose.desktop.application.dsl.TargetFormat
import org.jetbrains.kotlin.gradle.ExperimentalWasmDsl
import org.jetbrains.kotlin.gradle.dsl.JvmTarget

plugins {
    alias(libs.plugins.kotlinMultiplatform)
    alias(libs.plugins.androidApplication)
    alias(libs.plugins.composeMultiplatform)
    alias(libs.plugins.composeCompiler)
    alias(libs.plugins.composeHotReload)
    kotlin("plugin.serialization") version "2.1.21"
}

// ---- Build-time Environment (dev/prod) ------------------------------------
// Select profile with `-Penv=dev` (default) or `-Penv=prod`. Values are read
// from root gradle.properties and emitted as a generated commonMain source.

fun stripQuotes(s: String): String = s.trim().trim('"')
fun parseBaseUrl(url: String): Pair<String, String> {
    val trimmed = url.removeSuffix("/")
    return when {
        trimmed.startsWith("https://") -> "https" to trimmed.removePrefix("https://")
        trimmed.startsWith("http://") -> "http" to trimmed.removePrefix("http://")
        else -> "https" to trimmed
    }
}

val envProfile: String =
    (findProperty("env") as String?)
        ?: stripQuotes(findProperty("ENV_MODE") as String? ?: "dev")

val devHost: String = stripQuotes(findProperty("DEV_URL") as String? ?: "localhost")
val devPort: String = (findProperty("DEV_PORT") as String? ?: "10000")
val prodBase: String = stripQuotes(findProperty("API_BASE_URL") as String? ?: "https://example.com")
val prodPort: String = (findProperty("PROD_PORT") as String? ?: "443")


val envScheme: String = if (envProfile == "prod") parseBaseUrl(prodBase).first else "http"
val envHost: String = if (envProfile == "prod") parseBaseUrl(prodBase).second else devHost
val envPort: String = if (envProfile == "prod") prodPort else devPort

val generateEnvironment = tasks.register("generateEnvironment") {
    val outDir = layout.buildDirectory.dir("generated/environment/commonMain")
    outputs.dir(outDir)
    inputs.property("profile", envProfile)
    inputs.property("scheme",  envScheme)
    inputs.property("host",    envHost)
    inputs.property("port",    envPort)
    val capturedScheme = envScheme
    val capturedHost = envHost
    val capturedPort = envPort
    val capturedProfile = envProfile
    doLast {
        val dir = outDir.get().asFile.resolve("homeaq/dothattask/dothattask_fe/dothattask_fe/Config")
        dir.mkdirs()
        dir.resolve("Environment.kt").writeText(
            """
            package homeaq.dothattask.dothattask_fe.dothattask_fe.Config

            // Auto-generated by :composeApp:generateEnvironment. Do not edit by hand.
            object Environment {
                const val PROFILE: String = "$capturedProfile"
                const val SCHEME: String = "$capturedScheme"
                const val HOST: String = "$capturedHost"
                const val PORT: Int = $capturedPort
            }
            """.trimIndent(),
        )
    }
}

kotlin {
    androidTarget {
        compilerOptions {
            jvmTarget.set(JvmTarget.JVM_11)
        }
    }

    listOf(
        iosArm64(),
        iosSimulatorArm64()
    ).forEach { iosTarget ->
        iosTarget.binaries.framework {
            baseName = "ComposeApp"
            isStatic = true
        }
    }

    jvm()
    sourceSets {
        jvmMain.dependencies {
            implementation(compose.desktop.currentOs)
        }
    }

    js {
        browser()
        binaries.executable()
    }

    @OptIn(ExperimentalWasmDsl::class)
    wasmJs {
        browser()
        binaries.executable()
    }

    sourceSets {
        commonMain {
            kotlin.srcDir(generateEnvironment.map { layout.buildDirectory.dir("generated/environment/commonMain") })
        }
        androidMain.dependencies {
            implementation(compose.preview)
            implementation(libs.androidx.activity.compose)

            implementation(libs.ktor.client.android)
            implementation(libs.androidx.work.runtime.ktx.v290)
            implementation(libs.androidx.security.crypto)
        }
        commonMain.dependencies {
            implementation(compose.runtime)
            implementation(compose.foundation)
            implementation(compose.material3)
            implementation(compose.ui)
            implementation(compose.components.resources)
            implementation(compose.components.uiToolingPreview)
            implementation(libs.androidx.lifecycle.viewmodelCompose)
            implementation(libs.androidx.lifecycle.runtimeCompose)

            implementation(libs.kotlinx.serialization.json)

            implementation(libs.ktor.client.core)
            implementation(libs.ktor.client.auth)
            implementation(libs.ktor.client.content.negotiation)
            implementation(libs.ktor.serialization.kotlinx.json)




        }
        commonTest.dependencies {
            implementation(libs.kotlin.test)
        }

        jvmMain.dependencies {
            implementation(compose.desktop.currentOs)
            implementation(libs.kotlinx.coroutinesSwing)
            implementation(libs.ktor.client.cio)
        }


        jsMain.dependencies {
            implementation(libs.ktor.client.js)
        }

        wasmJsMain.dependencies {
            implementation(libs.ktor.client.wasm)
        }

        iosMain.dependencies {
            implementation(libs.ktor.client.darwin)
        }
    }
}

android {
    namespace = "homeaq.dothattask.dothattask_fe.dothattask_fe"
    compileSdk = libs.versions.android.compileSdk.get().toInt()


    defaultConfig {
        applicationId = "homeaq.dothattask.dothattask_fe.dothattask_fe"
        minSdk = libs.versions.android.minSdk.get().toInt()
        targetSdk = libs.versions.android.targetSdk.get().toInt()
        versionCode = 2
        versionName = "1.0.2"
    }
    packaging {
        resources {
            excludes += "/META-INF/{AL2.0,LGPL2.1}"
        }
    }

    //this is to sign the Android APK
    signingConfigs {
        if(hasProperty("RELEASE_STORE_FILE"))
        {
            create("release_debug") {   // <<< usa create() invece di "release { ... }"
                storeFile = file(property("RELEASE_STORE_FILE") as String)
                storePassword = property("RELEASE_STORE_PASSWORD") as String
                keyAlias = property("RELEASE_KEY_ALIAS") as String
                keyPassword = property("RELEASE_KEY_PASSWORD") as String
            }
        }
    }

    buildTypes {
        getByName("release") {
            isMinifyEnabled = false
            if(hasProperty("RELEASE_STORE_FILE")) {
                signingConfig = signingConfigs.getByName("release_debug")
            }
            isDebuggable = true
            isJniDebuggable = true

        }
    }
    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_11
        targetCompatibility = JavaVersion.VERSION_11
    }
}

dependencies {
    debugImplementation(compose.uiTooling)
}

compose.desktop {
    application {
        mainClass = "homeaq.dothattask.dothattask_fe.dothattask_fe.MainKt"

        nativeDistributions {
            targetFormats(TargetFormat.Dmg, TargetFormat.Msi, TargetFormat.Deb)
            packageName = "Do That Task"
            packageVersion = "1.0.2"
            includeAllModules = true
            windows {
                iconFile.set(File("logo/icon.ico"))
                perUserInstall = true
                dirChooser = true
                menuGroup = "DoThatTask"
                upgradeUuid = "A1B2C3D4-E5F6-7890-ABCD-EF1234567890"
            }
            modules("java.instrument", "java.management", "java.naming", "java.sql", "jdk.unsupported")
        }
        buildTypes.release.proguard {
            isEnabled.set(false)
        }
    }
}
